export const coursesInGhanaUniversities = {
  "courses_in_ghana_universities": [
    "Bachelor of Science in Administration (Accounting)",
    "Bachelor of Science in Administration (Banking & Finance)",
    "Bachelor of Science in Administration (Human Resource Management)",
    "Bachelor of Science in Administration (Public Administration)",
    "Bachelor of Science in Administration (Health Services Management)",
    "Bachelor of Science in Administration (Insurance)",
    "Bachelor of Science in Administration (Marketing)",
    "Bachelor of Arts (History)",
    "Bachelor of Arts (Philosophy and Classics)",
    "Bachelor of Arts (Study of Religions)",
    "Bachelor of Arts (Archaeology and Heritage Studies)",
    "Bachelor of Arts (English)",
    "Bachelor of Arts (French)",
    "Bachelor of Arts (Linguistics)",
    "Bachelor of Arts (Geography and Resource Development)",
    "Bachelor of Arts (Economics)",
    "Bachelor of Arts (Political Science)",
    "Bachelor of Arts (Psychology)",
    "Bachelor of Arts (Sociology)",
    "Bachelor of Arts (Social Work)",
    "Bachelor of Arts (Information Studies)",
    "Bachelor of Arts (Theatre Arts)",
    "Bachelor of Arts (Adult Education)",
    "Bachelor of Medicine and Bachelor of Surgery",
    "Bachelor of Dental Surgery",
    "Doctor of Pharmacy (PharmD)",
    "Bachelor of Science in Nursing",
    "Bachelor of Science in Computer Science",
    "Bachelor of Science in Agriculture",
    "Bachelor of Laws (LLB)",
    "Bachelor of Science in Engineering (Agricultural)",
    "Bachelor of Science in Engineering (Biomedical)",
    "Bachelor of Science in Engineering (Computer)",
    "Bachelor of Science in Engineering (Materials)",
    "Bachelor of Science in Family and Consumer Sciences",
    "Bachelor of Science in Dietetics",
    "Bachelor of Science in Medical Laboratory Sciences",
    "Bachelor of Science in Occupational Therapy",
    "Bachelor of Science in Physiotherapy",
    "Bachelor of Science in Radiography",
    "Bachelor of Science in Entomology and Wildlife",
    "Bachelor of Science in Agribusiness",
    "Bachelor of Commerce (Accounting)",
    "Bachelor of Commerce (Marketing)",
    "Bachelor of Education (Health, Physical Education and Recreation)",
    "Bachelor of Science in Actuarial Science",
    "Bachelor of Science in Psychology",
    "Master of Business Administration (MBA)",
    "Master of Public Health (MPH)",
    "Master of Science in Computer Science",
    "Master of Philosophy (MPhil) in Agricultural Economics",
    "Master of Arts in African Studies",
    "Master of Science in Biotechnology",
    "Master of Education (MEd)",
    "Master of Commerce (MCom)",
    "Master of Science in Forensic Accounting",
    "Doctor of Philosophy (PhD) in Animal Science",
    "Master of Science in Tax Policy & Finance",
    "Master of Science in Business Analytics",
    "Master of Science in Public Financial Administration",
    "Master of Science in Advance Practice Nursing",
    "Master of Arts in Religion and Human Values",
    "Diploma in Accounting",
    "Diploma in Public Administration",
    "Diploma in Adult Education",
    "Diploma in Information Technology",
    "Diploma in Cyber Security",
    "Certificate in Website Design",
    "Certificate in Mobile Phone Repairs",
    "Diploma in Electrical and Electronic Engineering",
    "Certificate in Digital Marketing",
    "Diploma in Procurement & Logistics",
    "MSc in Forensic Accounting and Fraud Examination",
    "MBA in Business Intelligence and Analytics",
    "MSc in Renewable Energy Technologies",
    "PhD in Integrated Coastal Zone Management",
    "Professional Certificate in Supply Chain Management",
    "Certified Information Systems Auditor (CISA)",
    "Ethical Hacking and Network Defense",
    "Unmanned Aerial Vehicle (Drone) Technology",
    "Leadership and Entrepreneurship Courses",
    "B.Sc. Biomedical Equipment Engineering",
    "B.Ed. Applied Technology (Electrical and Electronics)",
    "B.Ed. STEM (Engineering with Biomedical Science)",
    "B.Ed. Computing with Artificial Intelligence (AI)",
    "B.Ed. STEM (Engineering with Robotics)",
    "B.Sc. Cyber Security and Digital Forensics",
    "B.Sc. Procurement and Supply Chain Management",
    "B.Sc. Welding and Fabrication Technology with Education",
    "B.Sc. Wood Technology with Education",
    "B.Sc. Agricultural Science Education",
    "B.Ed. Agricultural Science",
    "B.Sc. Natural Resources Management and Education",
    "B.Sc. Agribusiness Management and Entrepreneurship Education",
    "B.Sc. Agricultural Engineering, Technology and Innovations Education",
    "B.Ed. General Science",
    "B.Ed. Biology",
    "B.Ed. Physics",
    "B.Ed. Chemistry",
    "B.Sc. Nutrition and Dietetics",
    "B.Sc. Public Health (Disease Control)",
    "B.Sc. Public Health (Nutrition)",
    "B.Sc. Public Health (Promotion)",
    "B.Sc. Occupational Health and Safety",
    "Diploma in Environmental Health and Sanitation",
    "Post Diploma (B.Sc.) Environmental Health and Sanitation",
    "2-Year Diploma in Junior High Education",
    "2-Year Diploma in Upper Primary Education",
    "2-Year Diploma in Early Grade Education",
    "Fundamentals of Innovation and Entrepreneurship (FIE)",
    "Text and Meaning",
    "Technology and Society",
    "Programming",
    "Leadership Series",
    "Doing Business in Africa"
  ]
}
